load("//build/kernel/kleaf:kernel.bzl", "ddk_headers", "ddk_module")
load("//driver_modules/wifi_bt/wifi:configs/wifi_ko_list.bzl", "driver_files")

driver_files()

ddk_module(
	name = "amlbt",
	srcs = [
			"w2_sdio_bt.c",
			"w2_pcie_bt.c",
			"w2_usb_bt_new.c",
			"amlbt.c",
			"common.c",
			"rc_list.c",
			"debug_dev.c",
			"amlbt_utils.c",
			"amlbt.h",
			"amlbt_utils.h",
			"common.h",
			"debug_dev.h",
			"gather_data.h",
			"rc_list.h",
			"w2_pcie_bt.h",
			"w2_sdio_bt.h",
			"w2_usb_bt_new.h",
		],
	hdrs = [
		"//common_drivers:soc_headers",
		"//driver_modules/wifi_bt/wifi/amlogic/w2:w2_comm_headers"
	],
	copts = [
		"-Wno-pointer-to-int-cast",
		"-Wno-implicit-fallthrough",
		"-Wno-format",
		"-Wno-incompatible-function-pointer-types",
		"-Wno-macro-redefined",
		"-Wno-strict-prototypes",
		"-Wno-unused-variable",
		"-Wno-incompatible-pointer-types",
	],
	out = "aml_bt.ko",
	kernel_build = "//common_drivers:amlogic",
	visibility = ["//visibility:public"],
	deps = [
		"//common_drivers/drivers/pm:amlogic-pm",
		"//driver_modules/wifi_bt/wifi/amlogic/w2:w2_comm",
	],
)
